services:
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.10.2
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas requests mysqlclient"
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create -u admin -p admin -r Admin -e admin@example.com -f Admin -l User"

  airflow-webserver:
    image: apache/airflow:2.10.2
    container_name: airflow_webserver
    depends_on:
      - airflow-init
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__RBAC: "True"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas requests mysqlclient"
    volumes:
      - C:\Users\remyh\Documents\COURS\nexa\renf python\docker/dags:/opt/airflow/dags
      - C:\Users\remyh\Documents\COURS\nexa\renf python\docker/logs:/opt/airflow/logs
      - C:\Users\remyh\Documents\COURS\nexa\renf python\docker/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.10.2
    container_name: airflow_scheduler
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas requests mysqlclient"
    volumes:
      - C:\Users\remyh\Documents\COURS\nexa\renf python\docker/dags:/opt/airflow/dags
      - C:\Users\remyh\Documents\COURS\nexa\renf python\docker/logs:/opt/airflow/logs
      - C:\Users\remyh\Documents\COURS\nexa\renf python\docker/plugins:/opt/airflow/plugins
    command: scheduler

volumes:
  postgres_db:
